### ISSUE TITLE
Small copy-pasta in the fb_ethtool README.md

### ISSUE THREAD

**Issue by misheska** [facebook/chef-cookbooks#118]
References `fb_screen` when it should be `fb_ethtool`:

 "You can opt out of package management by settings node['fb_screen']['manage_packages'] to false."

**Comment by joshuamiller01** [comment]
Shame on us; I'll fix.

**Comment by joshuamiller01** [comment]
Fixed with https://github.com/facebook/chef-cookbooks/commit/cf3f297014081f030fea67c8fc78c48f0ab5febc
