### ISSUE TITLE
Publishing to supermarket.chef.io

### ISSUE THREAD

**Issue by supercharger** [facebook/chef-cookbooks#17]
Can we publish these to supermarket.chef.io ?

**Comment by jaymzh** [comment]
So... it's a bit complicated. Using these with other cookbooks that don't follow this model is going to end in a **very bad time**. Also, these cookbooks are not versioned (or rather, their version will never change). Wrapper cookbooks must go after, not before, in your runlist. So I was waiting for the namespace discussion to die down a bit and we'll re-look at it... so it's on the list of things to revisit.

**Comment by jaymzh** [comment]
All of these are now on Supermarket. THere's not yet automation on keeping them uptodate though, but they're there. We're moving to Circle and will add auto-publishing to SM as part of that.

**Comment by jaymzh** [comment]
The automation was made, but then, because Chef broke that flow, all torn back down. I'm closing this now, because Supermarket explicitly doesn't allow us to push to it anymore... because you can never push an update if the version number doesn't change. :(
