### ISSUE TITLE
fb_helpers contains namespace collisions with official chef node objects

### ISSUE THREAD

**Issue by erikng** [facebook/chef-cookbooks#211]
In chef v17, chef added a lot of built-ins and we are seeing instability with at least one of them

https://github.com/facebook/chef-cookbooks/blob/main/cookbooks/fb_helpers/libraries/node_methods.rb#L146

when we call `debian?` within a library function, it returns false, so we are now having to do `debian? || ubuntu?` to workaround this as we consume fb_helpers.

To put this nicely, is Facebook willing to stop doing this? Or at the very least, stop putting so many of these things in `node` and put it to a FB namespace?

**Comment by jaymzh** [comment]
First, I'm not sure why these would cause instability - those methods are in the DSL namespace and not on the node, and should in no way conflict.

Second, yes, once FB is fully on Chef 17, it will likely make sense for them to code-mod away from the node methods to the DSL methods, and then deprecate these and remove them, but that's not going to happen over night, so we should figure out why you're having issues with these.

**Comment by erikng** [comment]
We agree on the confusion around DSL/Node. We are also seeing some weird behavior with `shell_out` on similar helpers but didn't want to discuss two issues at once. 

Both are quite confusing though.

**Comment by jaymzh** [comment]
I use `shell_out` a lot in C17 and have had no issues.

If you wanna provide a working example of how `debian?` doesn't work as expected when fb_helpers is defined, but not otherwise, I can certainly look into it

**Comment by erikng** [comment]
I need to figure out how to distill it down as the code is deep in our internal libraries. And yeah what's weird is the shell out work just fine on macOS, but not Ubuntu 20. It's very puzzling. 

For now we are instead calling `debian_family?` which doesn't seem to hit this issue.

**Comment by jaymzh** [comment]
That ... would be the expected behavior. `debian?` won't match Ubuntu 20 but `debian_family?` would.

**Comment by erikng** [comment]
*sigh*

I'll close this ticket and create another one once I figure out more info on the shell out.

**Comment by erikng** [comment]
We should have looked at this more closely before pointing fingers so apologies about that.

**Comment by erikng** [comment]
This also impacts things like

```
chef (17.8.25)> node.serial
[2022-02-17T12:25:48-05:00] WARN: ubuntu is not yet supported by node.serial
 => nil 
```

and the logic actually works just fine except `debian?` is what's being rejected

```
erikg@erikg-VMwareVirtualPlatform:~$ sudo /usr/sbin/dmidecode -s system-serial-number
VMware-56 4d ca 0e 2b de 73 27-31 4b 67 81 d1 83 4f ec
```

**Comment by erikng** [comment]
The latter option is something I was thinking about but yeah, none of this is ideal :/

**Comment by dafyddcrosby** [comment]
Meant to chime in on this one (I thought I already had, sorry!). The wrapper method approach is probably the one we'll end up taking, though not sure about the codemod aspects of removing `node.` yet, as the `node` object does make inferring what's going on easier when doing static analysis. We might make a Cookstyle lint to catch direct (ie non-wrapper method) use of ChefUtils::DSL, so that there's a consistent way of handling this problem.

**Comment by jaymzh** [comment]
Well, the non-node varieties are mixed into the Recipe DSL, so they're easy to reason about. No different than `file`, or `directory` or anything else in the DSL.

**Comment by jaymzh** [comment]
I've been working on transitioning the most egregious of these, but it'll be a long road.

However, this should only be a problem in `attributes` files. Everywhere else ChefUtils should take precedent.

In attributes files you can work around this with `::ChefUtils.debian?`

**Comment by jaymzh** [comment]
@erikng - Sorry for dropping this, we were working on other stuff - but the attached PR should provide both an explicit way to call ChefUtils, and a way for us to migrate.
