### ISSUE TITLE
node.antlir_build? not defined in open source

### ISSUE THREAD

**Issue by taylorific** [facebook/chef-cookbooks#223]
Hi all, it looks like the `node.antlir_build?` function is not defined that is referenced in the `fb_syslog` cookbook:
https://github.com/facebook/chef-cookbooks/blob/7cbfb039b3e83b4c2426763bf963d5ea8eb19d27/cookbooks/fb_syslog/recipes/packages.rb#L25

Any chance of providing a definition for this in the open source `fb_helpers` so we can use this cookbook unmodified, if it is needed?

**Comment by davide125** [comment]
This is an internal thing that shouldn't have been published to an opensource cookbook in the first place. Sorry for the noise, we'll get it fixed. cc @dafyddcrosby

**Comment by taylorific** [comment]
Awesome, thanks!
