### ISSUE TITLE
Definitions for antlir2 fix are not exposed in open source

### ISSUE THREAD

**Issue by taylorific** [facebook/chef-cookbooks#230]
Hi all - this commit seems to have definitions that aren't in the open source exposed to the public:
https://github.com/facebook/chef-cookbooks/commit/6baf374a6b2a6cdad61c641a04fb0495a0ba821c

I don't see a `fb_util` or a definition for `antlir2_build?` and this commit prevents use of `fb_systemd` due to missing definitions.

**Comment by davide125** [comment]
Yes, this shouldn't have been merged. @dafyddcrosby we need to revert this

**Comment by taylorific** [comment]
Thanks, no worries. Appreciate that you're open sourcing these awesome cookbooks!
