### ISSUE TITLE
vs_ftpd service does not respect disable setting

### ISSUE THREAD

**Issue by misheska** [facebook/chef-cookbooks#35]
https://github.com/facebook/chef-cookbooks/blob/master/cookbooks/fb_vsftpd/recipes/default.rb#L69

The `disable vsftpd` service resource does not include `service_name vsftpd` so it errors when `node['fb_vsftpd']['enable'] == false`

**Comment by davide125** [comment]
Thanks for reporting! I will have this fixed soon.
