### ISSUE TITLE
get_seeded_flexible_shard in fb_cron appears to be missing from public repo

### ISSUE THREAD

**Issue by misheska** [facebook/chef-cookbooks#43]
When you set `splaysecs` the `fb_cron` cookbook references the` node.get_seeded_flexible_shard()`. This method does not appear to be publicly available.

**Comment by joshuamiller01** [comment]
Yea - this should be in `fb_helpers`, but it isn't.  I'll look at getting it added.

**Comment by joshuamiller01** [comment]
Should be fixed now.
