### ISSUE TITLE
apt-key does not output short key IDs in debian 9

### ISSUE THREAD

**Issue by chrisrlong** [facebook/chef-cookbooks#52]
Hi,

The provider code:

 if keys && keyring
    installed_keys = []
    if ::File.exist?(keyring)
      cmd = Mixlib::ShellOut.new("LANG=C apt-key --keyring #{keyring} list")
      cmd.run_command
      cmd.error!
      output = cmd.stdout.split("\n")
      Chef::Log.debug("apt-key output: #{output.join("\n")}")
      installed_keys = output.select { |x| x.start_with?('pub') }.map do |x|
        **x[%r{pub.*/(?<keyid>[A-Z0-9]*)}**, 'keyid']
      end
    end

Does not detect the debian 9 apt-key output:

pub   rsa4096 2016-10-05 [SC]
      72EC F46A 56B4 AD39 C907  BBB7 1646 B01B **86E5 0310**
uid           [ unknown] Yarn Packaging <yarn@dan.cx>

Every chef pass reinstalls all the keys.

**Comment by chrisrlong** [comment]
please see PR #53

**Comment by malmond77** [comment]
Thanks for the report, and the PR. Let's follow up there.
