### ISSUE TITLE
fb_zfs fails on every single supported distro

### ISSUE THREAD

**Issue by jaymzh** [facebook/chef-cookbooks#79]
all centos and all debian/ubuntus fail for something equivalent to:
```
No candidate version available for spl, spl-dkms, zfs-dkms, zfsutils-linux
```

**Comment by nicolasgoudard** [comment]
UP

**Comment by jaymzh** [comment]
@nicolasgoudard after talking to some folks it sounds like this cookbook is probably just gonna get deleted. No one is using it anymore.

@davide125 is that still the plan?

**Comment by davide125** [comment]
Yes, this has been broken and unsupported for years, and I don't have any way to test it nowadays. Unless someone that's actually using ZFS wants to fix it and keep it working, it'll get deleted soon.

**Comment by nicolasgoudard** [comment]
Hi, thx. It's ok now, I follow this tutorial https://openzfs.github.io/openzfs-docs/Getting%20Started/Debian/Debian%20Buster%20Root%20on%20ZFS.html

`sudo vi /etc/apt/sources.list`

Then add 

```
deb http://deb.debian.org/debian buster main contrib
deb http://deb.debian.org/debian buster-backports main contrib
```
